apiVersion: backstage.io/v1alpha1
kind: Silly
metadata:
  name: bingo
  title: Bingo
  description: GitHub Action that updates the version of a package by commenting on a PR
spec:
  type: github action
  lifecycle: Deceased
  dependsOn:
    - "Resource:github-actions"
  consumesAPI:
    - github-rest-api
  system: github
