apiVersion: backstage.io/v1alpha1
kind: whoopsies
metadata:
  name: Bingo
  title: bingo
  description: GitHub Action that updates the version of a package by commenting on a PR
spec:
  type: github action
  lifecycle: afterlife
  dependsOn:
    - "Resource:github-actions"
  consumesAPI:
    - github-rest-api
  system: github
