apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dobby
  title: Dobby
  description: GitHub Action that updates the version of a package by commenting on a PR
  annotations:
    ownership/business-owner: silversmiths
spec:
  type: github action
  lifecycle: production
  dependsOn:
    - "Resource:github-actions"
  consumesAPI:
    - github-rest-api
  system: github
